# Ubuntu 14.04 Trusty support
sudo: required
dist: trusty
language: node_js
node_js:
  - "5.1"
notifications:
  email: false
services: mongodb
install:
  - cd api/
  - npm install
script:
  - which mongod
  - cd tests/
  - ./initializeTestDatabase.sh
  - ../node_modules/mocha/bin/mocha .
